# Do not edit this file, copy this file & rename it to const.py. Any format error will result in not getting start or help message.

from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton


START_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🆘 Help", callback_data="help_cb"),
            InlineKeyboardButton(
                "👨‍💻 Source Code", url="https://github.com/EL-Coders/groupfilter"
            ),
        ]
    ]
)
HELP_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)


START_MSG = "Hi **[{}](tg://user?id={})**, I am a an autofilter bot which finds & shares media from my database."

HELP_MSG = """
**You can find the bot commands here.**
**Group Commands:-**
‣/help - __Show this help message__
‣/settings - __Toggle settings of Precise Mode and Button Mode__
`Precise Mode:` 
- __If Enabled, bot will match the word & return results with only the exact match__
- __If Disabled, bot will match the word & return all the results containing the word__ 
`Result Mode:` 
- __If Button, bot will return results in button format__
- __If List, bot will return results in list format__
- __If HyperLink, bot will return results in hyperlink format__

**Admin Commands:-**
‣/logs - __Get logs as a file__
‣/server - __Get server stats__
‣/restart - __Restart the bot__
‣/stats - __Get bot user stats__
‣/broadcast - __Reply to a message to send that to all bot users__
‣/index - __Start indexing a database channel (bot must be admin of the channel if that is private channel)__
__You can just forward the message from database channel for starting indexing, no need to use the /index command__
/indexlink - __Start indexing a database channel using link (bot must be admin of the channel if that is private channel)__
__`/indexlink <last message link>` or `/indexlink <start message link> <last message link>`__
‣/delete - __Reply to a file to delete it from database__
‣/autodelete - __Set file auto delete time in seconds__
‣/buttondel - __Set button message in groups auto delete time in seconds__
‣/repairmode - __Enable or disable repair mode - If on, bot will not send any files__
‣/customcaption - __Set custom caption for files__ - `/customcaption caption/off`
‣/setcaptionplus - __Set additional caption for files along with caption__ - `/setcaptionplus caption/off`
‣/adminsettings - __Get current admin settings__
‣/ban - __Ban a user from bot__ - `/ban user_id`
‣/unban - __Unban a user from bot__ - `/unban user_id`
‣/addfilter - __Add a text filter__ - `/addfilter filter message` __or__ `/addfilter "filter multiple words" message` __(If a filter is there, bot will send the filter rather than file)__
‣/delfilter - __Delete a text filter__ - `/delfilter filter`
‣/listfilters - __List all filters currently added in the bot__
‣/forcesub - __Set force subscribe channel__ - `/forcesub channel_id/off` __or__ `/forcesub channel_id request`(for request channel) __Bot must be admin of that channel (Bot will create a new invite link for that channel)__
‣/clearfsubusers - __Clear all force subscribe users from db__
‣/checklink - __Check invite link for force subscribe channel__
‣/infomsg - __Set info message before sending file__ - `/infomsg message/off`
‣/infoimg - __Set info image before sending file__ - Reply `/infoimg` to an image to set or  `/infoimg off` to remove
‣/delmsg - __Set delete message after sending file (File auto delete needs to be enabled to work)__ - `/delmsg message/off`
‣/delimg - __Set delete image after sending file (File auto delete needs to be enabled to work)__ - Reply `/delimg` to an image to set or  `/delimg off` to remove
‣/notfoundmsg - __Set message to send when file not found__ - `/notfoundmsg message/off`
‣/notfoundimg - __Set image to send when file not found__ - Reply `/notfoundimg` to an image to set or  `/notfoundimg off` to remove
‣/fsubmsg - __Set force subscribe message__ - `/fsubmsg message/off`
‣/fsubimg - __Set force subscribe image__ - Reply `/fsubimg` to an image to set or  `/fsubimg off` to remove
‣/total - __Get count of total files in DB__
"""
