# Do not edit this file, copy this file & rename it to const.py. Any format error will result in not getting start or help message.

from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
import re

START_IMG = ["https://envs.sh/gOJ.jpg?=ilovSTARLEY","https://envs.sh/gOo.jpg?=ilovSTARLEY","https://envs.sh/gO9.jpg?=ilovSTARLEY","https://envs.sh/gOs.jpg?=ilovSTARLEY","https://envs.sh/gOr.jpg?=ilovSTARLEY","https://envs.sh/gOv.jpg?=ilovSTARLEY","https://envs.sh/gON.jpg?=ilovSTARLEY",]
NOT_F_IMG = "AgACAgUAAxkBAAIJQ2hKXfrY8nRU5k3kaqZ5az_ElekZAAK2yDEbHNpZVj-gSnCNBV9RAAgBAAMCAAN5AAceBA"

def get_start_kb(bot_username):
    return InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "➕ Add Me To Your Groups ➕",
                    url=f"http://t.me/{bot_username}?startgroup=true",
                )
            ],
            [
                InlineKeyboardButton(
                    "🪄 Oᴡɴᴇʀ 🪄", url="https://t.me/Sathan_Of_Telegram"
                ),
            ],
            [
                InlineKeyboardButton(
                    "⚠️ Group 1 ⚠️", url="https://t.me/Cinemathattakam_Group"
                ),
                InlineKeyboardButton(
                    "✨ Group 2 ✨", url="https://t.me/Cinemathattakam_Group1"
                ),
            ],
            [
                InlineKeyboardButton(
                    "🥇 Mᴀɪɴ Cʜᴀɴɴᴇʟ 🥇", url="https://t.me/CT_Arena"
                )
            ],
        ]
    )
    

START_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🆘 Help", callback_data="help_cb"),
            InlineKeyboardButton(
                "👨‍💻 Source Code", url="https://t.me/CT_Updatez/13"
            ),
        ]
    ]
)


HELP_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)


HELP_MOD_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🚫 Bans", callback_data="hlp_ban"),
            InlineKeyboardButton("💬 Custom Messages", callback_data="hlp_cstmsg"),
        ],
        [
            InlineKeyboardButton("📝 Custom Captions", callback_data="hlp_ccptn"),
            InlineKeyboardButton("🗑️ Delete", callback_data="hlp_del"),
        ],
        [
            InlineKeyboardButton("📱 Force Sub", callback_data="hlp_fsub"),
            InlineKeyboardButton("📝 Filters", callback_data="hlp_fltr"),
        ],
        [
            InlineKeyboardButton("📚 Index", callback_data="hlp_indx"),
            InlineKeyboardButton("📢 Promotions", callback_data="hlp_promo"),
        ],
        [
            InlineKeyboardButton("⚙️ Settings", callback_data="hlp_sets"),
            InlineKeyboardButton("📊 Utilities", callback_data="hlp_utls"),
        ],
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)


HELP_BK_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="helpmod_cb"),
        ],
    ]
)



def nf_kb(search):
    search = re.sub(r"\s+", "+", search.strip())
    return InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton(
                "🔍 Sᴇᴀʀᴄʜ Tʜᴇ Cᴏʀʀᴇᴄᴛ Sᴘᴇʟʟɪɴɢ Fʀᴏᴍ Gᴏᴏɢʟᴇ...🔎",
                url=f"https://www.google.com/search?q={search}",
            )
        ],
        [
            InlineKeyboardButton(
                "🎭 Rᴇᴘᴏʀᴛ Fᴏʀ Rᴀʀᴇ Mᴏᴠɪᴇ 🎭",
                url=f"https://t.me/Hannibal_Lectarbot?start=true"
            )
        ]
    ]
    )

REPAIR_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("⭕️ 𝗨𝗽𝗱𝗮𝘁𝗲 𝗖𝗵𝗮𝗻𝗻𝗲𝗹 ⭕️", url="https://t.me/CT_Updatez"),
        ],
    ]
)


START_MSG = "Hᴇʏ Tʜᴇʀᴇ {}, Mʏ Nᴀᴍᴇ ɪs **{}** .\n\n**Yᴏᴜʀ Mᴀɢɪᴄᴀʟ Assɪsᴛᴀɴᴛ Fᴏʀ Fɪɴᴅɪɴɢ Fɪʟᴇs Iɴ A Fʟᴀsʜ!**\n**Jᴜsᴛ Tᴇʟʟ Mᴇ Wʜᴀᴛ Yᴏᴜ'ʀᴇ Lᴏᴏᴋɪɴɢ Fᴏʀ — Mᴏᴠɪᴇs, Sᴇʀɪᴇs, Dᴏᴄᴜᴍᴇɴᴛs — Aɴᴅ Pᴏᴏғ! 🎩✨ I’ʟʟ Fᴇᴛᴄʜ Iᴛ Fᴏʀ Yᴏᴜ Iɴsᴛᴀɴᴛʟʏ...**\n**Jᴜsᴛ Aᴅᴅ Mᴇ Iɴ Yᴏᴜʀ Gʀᴏᴜᴘs,Oʀ Jᴜsᴛ Sᴇɴᴅ Mᴏᴠɪᴇ Nᴀᴍᴇ Hᴇʀᴇ, **\n\n>  **I'ᴍ Rᴇᴀᴅʏ Tᴏ Assɪsᴛ ʏᴏᴜ 24/7! 🕒**"


HELP_MSG = """
**You can find the bot commands here.**

‣ /help - __Show this help message__

>**Tap on corresponding modules to get the commands of that module.**
"""


PROMO_HLP_MSG = """
>**Manage Promotional Links**
>__Easily add, delete, or view promotional links displayed between search results.__

‣ /addpromo - __Set promotional links between results__ - `/addpromo "Button Text" URL`
‣ /delpromo - __Delete promotional links between results__ - `/delpromo URL`
‣ /listpromos - __List all promotional links currently added in the DB__
"""

FSUB_HLP_MSG = """
>**Force Subscription Management**
>__Set, manage, or clear force subscribe channels.__ 

‣ /setfsubcount - __Set maximum Fsub chat count for queue (If not set, queued FSub will be activated instantly)__
‣ /setfsub - __Set force subscribe channel__ - `/forcesub channel_id` (Answer the questions after that) __Bot must be admin of that channel (Bot will create a new invite link)__
‣ /rmfsub - __Remove force subscribe channel__ - `/rmfsub channel_id`
‣ /rmallfsub - __Remove all force subscribe channels__
‣ /getallfsub - __Get all force subscribe channel details__
‣ /getactivefsub - __Get active force subscribe channels__
‣ /getpendingfsub - __Get pending force subscribe channels which is in queue__
‣ /activatefsub - __Activate pending force subscribe channel__ - `/activatefsub channel_id`
‣ /deactivatefsub - __Deactivate force subscribe channel__ - `/deactivatefsub channel_id`
‣ /updatefsubtarget - __Update force subscribe channel target__ - `/updatefsubtarget channel_id target`
‣ /checkfsubusers - __Check force subscribe users count__
‣ /clearfsubusers - __Clear all force subscribe users from db__
"""

FLTR_HLP_MSG = """
>**Filter Management**
>__Add, delete, or view filters to customize responses based on keywords.__

‣ /addfilter - __Add a text filter__ - Reply `/addfilter keyword` to a message to set __(If a filter is there, bot will send the filter rather than file)__
‣ /delfilter - __Delete a text filter__ - `/delfilter filter`
‣ /listfilters - __List all filters currently added in the bot__

__Supports text/photo/video/animation/sticker__
"""

BAN_HLP_MSG = """
>**User Management**
>__Ban or unban users to control access to the bot.__

‣ /ban - __Ban a user from bot__ - `/ban user_id`
‣ /unban - __Unban a user from bot__ - `/unban user_id`
"""

CUST_MSG_HLP_MSG = """
>**Custom Messages & Images**
>__Configure custom messages and images for various actions, such as file info, file deletion, file not found, or force subscription prompts.__

‣ /infomsg - __Set info message before sending file__ - Reply `/infomsg` to a message to set or  `/infomsg off` to remove
‣ /infoimg - __Set info image before sending file__ - Reply `/infoimg` to an image to set or  `/infoimg off` to remove
‣ /delmsg - __Set delete message after sending file (File auto delete needs to be enabled to work)__ - Reply `/delmsg` to a message to set or  `/delmsg off` to remove
‣ /delimg - __Set delete image after sending file (File auto delete needs to be enabled to work)__ - Reply `/delimg` to an image to set or  `/delimg off` to remove
‣ /notfoundmsg - __Set message to send when file not found__ - Reply `/notfoundmsg` to a message to set or  `/notfoundmsg off` to remove
‣ /notfoundimg - __Set image to send when file not found__ - Reply `/notfoundimg` to an image to set or  `/notfoundimg off` to remove
‣ /fsubmsg - __Set force subscribe message__ - Reply `/fsubmsg` to a message to set or  `/fsubmsg off` to remove
‣ /fsubimg - __Set force subscribe image__ - Reply `/fsubimg` to an image to set or  `/fsubimg off` to remove
"""

CAP_HLP_MSG = """
>**File Caption Management**
>__Manage or customize captions for files, including additional captions, to enhance file presentation.__

‣ /customcaption - __Set custom caption for files__ - Reply `/customcaption` to a message to set or `/customcaption off` to disable.
‣ /captionplus - __Set additional caption for files along with caption__ - Reply `/captionplus` to a message to set or `/captionplus off` to disable.
"""

DEL_HLP_MSG = """
>**File/Auto Deletion Management**
>__Delete files from the database or configure auto-delete settings for files and button messages in groups.__

‣ /delete - __Reply to a file to delete it from database__
‣ /delmulti - __Delete multiple files from database with name__ - `/delmulti name`
‣ /autodelete - __Set file auto delete time in seconds__
‣ /buttondel - __Set button message in groups auto delete time in seconds__
"""

INDX_HLP_MSG = """
>**Database Indexing**
>__Index a database channel by forwarding messages or using links. Supports private channels if the bot is an admin.__

‣ /index - __Start indexing a database channel (bot must be admin of the channel if that is private channel)__
__You can just forward the message from database channel for starting indexing, no need to use the /index command__
‣ /indexlink - __Start indexing a database channel using link (bot must be admin of the channel if that is private channel)__
__`/indexlink last_message_link` or `/indexlink start_message_link last_message_link`__
"""

SET_HLP_MSG = """
>**Bot Settings Management**
__Customize behavior, including result formats (Button, List, or Hyperlink), enabling repair mode, and viewing admin settings.__

‣ /repairmode - __Enable or disable repair mode - If on, bot will not send any files__
‣ /adminsettings - __Get current admin settings__
"""

UTIL_HLP_MSG = """
>**Utility Commands**
>__Access bot logs, server stats, restart the bot, get user and file counts, send broadcasts, and more.__

File Utilities:
‣ /total - __Get count of total files in DB__
‣ /clearfiles - __Clear all files from DB__
‣ /clearusers - __Clear all users from DB__
‣ /clearfsubusers - __Clear all force subscribe users from db__
‣ /channelpost - __Post search link to channels__

Admin Utilities:
‣ /logs - __Get logs as a file__
‣ /server - __Get server stats__
‣ /restart - __Restart the bot__
‣ /stats - __Get bot user stats (Will send only after checking active users__
‣ /broadcast - __Reply to a message to send that to all bot users__

"""

REPAIR_MSG = """
>**Bᴏᴛ Is Uɴᴅᴇʀ Mᴀɪɴᴛᴇɴᴀɴᴄᴇ...! 🔧🤖⚙️**
>**Pʟᴇᴀsᴇ Bᴇ Pᴀᴛɪᴇɴᴛ**
>
>**Fᴜʀᴛʜᴇʀ Uᴘᴅᴀᴛᴇs Wɪʟʟ Bᴇ Uᴘᴅᴀᴛᴇᴅ Iɴ Oᴜʀ Uᴘᴅᴀᴛᴇ Cʜᴀɴɴᴇʟ**
>**Jᴏɪɴ Tʜᴇ Bᴇʟᴏᴡ Cʜᴀɴɴᴇʟ Aɴᴅ Wᴀɪᴛ 🫷**"""

def nf_txt(mention, search): 
    return f"𝗛ᴇʏ **{mention}**,\n>✧ **Mᴏᴠɪᴇ Nᴏᴛ Fᴏᴜɴᴅ Iɴ Mʏ DB🔍🙇.**\n**✧ OTT Nᴏᴛ Rᴇʟᴇᴀsᴇᴅ,\n✧ Sᴘᴇʟʟɪɴɢ Is Wʀᴏɴɢ**\n✧ ** Tʀʏ Sᴇᴀʀᴄʜɪɴɢ  `{search}` ᴏɴ Gᴏᴏɢʟᴇ!**\nIғ Sᴘᴇʟʟɪɴɢ Is Cᴏʀʀᴇᴄᴛ & OTT Is Rᴇʟᴇᴀsᴇᴅ, Tʜᴇɴ Rᴇᴘᴏʀᴛ Fᴏʀ Rᴀʀᴇ Mᴏᴠɪᴇ Bʏ Cʟɪᴄᴋɪɴɢ Sᴇᴄᴏɴᴅ Bᴜᴛᴛᴏɴ ✨"


def res_txt(mention, search, botmention, count, crnt_pg, tot_pg):
    return f"𝐇𝐞𝐲 𝐓𝐡𝐞𝐫𝐞 **{mention}** 𝐓𝐡𝐢𝐬 𝐈𝐬 𝐖𝐡𝐚𝐭 𝐈 𝐅𝐨𝐮𝐧𝐝 𝐅𝐨𝐫 𝐘𝐨𝐮𝐫 𝐐𝐮𝐞𝐫𝐲 📂\n\n**★ Aғᴛᴇʀ 1 Mɪɴᴜᴛᴇ Yᴏᴜʀ Bᴜᴛᴛᴏɴs Wɪʟʟ Bᴇ Aᴜᴛᴏᴍᴀᴛɪᴄᴀʟʟʏ Dᴇʟᴇᴛᴇᴅ ★**\n\n**Jᴏɪɴ Oᴜʀ Gʀᴏᴜᴘs** : [💥Cɪɴᴇᴍᴀᴛʜᴀᴛᴛᴀᴋᴀᴍ 💥](https://t.me/addlist/euBsJ9YAMKYxMmRl)\n\n> ┏**Tᴏᴛᴀʟ Rᴇsᴜʟᴛs** : {count} \n> ┗**Pᴀɢᴇs** {crnt_pg}/{tot_pg}"


REMOVE_WORDS = [
    "[MCU]", "@WMR", "Dramaost", "@R A R B G", "AMZN", "WEBDL", "WEB DL", "DVDRip", "HDRip", "HDTV", 
    "rarbg", "HSWEBDL", "10Bit", "WEBRip", "AAC", "DD5 1", "6CH", "2CH", "DDP5 1", "Mp3", "ESub", "EAC3", 
    "Uncut", "192Kbps", "HQ", "AVC", "UNTOUCHED", "mp4", "bluray", "@Ava", "384kbps", "192kbps", "WEB-DL", 
    "ZEE5", "10 bit", "10bit", "XVid", "unrated", "avc", "Hswebdl", "@MM LINKZ", "[MZM]", "@IM", "IMAX", 
    "EXTENDED", "viki", "iqiyi", "Seriesland4u", "DSNP", "DVDWO", "@MM OLD", "@CC", "Atmos", "Mubi", "AAC2 0", 
    "Repack", "proper", "Seriesland", "Mallu hub", "Mallumovies", "Mallumv", "Tamilmv", "Tamilrockers", "www", 
    "Directors cut", "FC_HEVC", "CDL", "Cdrama", "Kdrama", "Kdramaforyouall", "Ccineclub", "400MB", "250MB", 
    "500mB", "700MB", "900MB", "1600MB", "950MB", "600MB", "intermedia", "Sample", "CPTN5DW", "JrRip", "SH3LBY", 
    "Telly", "Primefix", "mkvCinemas", "HEvcbay", "Mkvking", "Dramahub", "Dramaday", "NF Webdl", "DDP5.1", 
    "Adrama Lovers", "TBPINDEX", "MZM", "MOVIEZ", "RAREFILMS", "Raremoviez", "backup", "Open matte", "AAC5.1 1", 
    "MCU", "YTS", "FULLHD", "HDSECTOR", "Extended", "vmax", "yessma", "king.com", "Divxtotal", "Tuktukcinema", 
    "Cimaclub.com", "Shahid4U.com", "Aflamfree", "backup", "DA Rips", "HDMovies", "kbps", "IMEDIASHARE", 
    "Rickychannel", "mubimovies", "CC ALL", "Infotainment", "mkvcage", "movie mania", "[Dno]", "zeemarathimovies", 
    "C C Channel", "WMR", "UCParadiso", "imovieshare", "Team HDT", "TeamHDT", "Toonsworld4all", "INTERNAL", "DnO", 
    "Cinemavilla", "Ongoing", "MMAX", "MM OLD", "[MM]", "Cinema naab", "NSSS", "[", "]", "mkv", "@MM", "Adrama", 
    "Toonworld4all", "SONYLIV", "SS DD 5 1", "DD 5 1", "CC Telugu", "Cc Tamil", "cc new", "hindimovies", "bm links", 
    "mm links", "Piro", "DS4K", "DDP5 1", "DDP 5 1", "voot", "Fanszz", "Tv2us", "CC ALL", "AAC2 0", "AAC", "(", ")", 
    "Ddp2 0", "FBM ALL", "FB TAMIL", "FBM HW", "FBM NEW", "FBM x265", "FBM KOREAN", "FBM", "KICKASS", "TORRENTS", 
    "@", "Dubbed", "Tamilblasters", "dubb", "ssrreq", "VGCINEMAS", "SNXT", "TG SKY MOVIES HD", "@R_A_R_B_G", "R_A_R_B_G"
]

STOP_WORDS = []
